spring:
  application:
    name: petshop

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/petshop}
    username: ${DATASOURCE_USER:petshop}
    password: ${DATASOURCE_PWD:pwdpetshop}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: create-drop   # create, create-drop, validate, none, update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MySQLDialect